<!DOCTYPE html>
<meta charset="utf-8">
<title>Server Error</title>

<style>
	body { color: #333; background: #fff; width: 500px; margin: 100px auto; font: 16px/1.5 sans-serif; }
	h1 { font-size: 47px; margin: 10px 0; }
</style>

<h1>Server Error</h1>

<p>We're sorry! The server encountered an internal error and was unable to complete your request. Please try again later.</p>

<p><small>error 500</small></p>
